Repository PyDMD/PyDMD, pull requests merged in 2023-07, with the labels that each got.

#416 Some more changes in readme
  README.md
Labels: maintenance

#427 Bump GitHub PR action version
  .github/workflows/export_tutorials.yml
  tutorials/tutorial15/tutorial-15-pidmd.ipynb
Labels: maintenance

#429 Dummy update to trigger action
  tutorials/tutorial15/tutorial-15-pidmd.ipynb
Labels: maintenance

#431 BOP-DMD with eigenvalue constraints
  pydmd/bopdmd.py
  tests/test_bopdmd.py
Labels: enhancement

#433 Randomized DMD Tutorial
  pydmd/rdmd.py
  tutorials/README.md
  tutorials/tutorial16/tutorial-16-rdmd.ipynb
Labels: tutorials

#432 Fixed major variable projection bug in `BOPDMD`
  pydmd/bopdmd.py
Labels: bug
