Repository PyDMD/PyDMD, pull requests merged in 2023-01, with the labels that each got.

#306 Snapshots shape normalization improvements
  pydmd/cdmd.py
  pydmd/dmd.py
  pydmd/dmdbase.py
  pydmd/dmdc.py
  pydmd/hankeldmd.py
  pydmd/havok.py
  pydmd/hodmd.py
  pydmd/mrdmd.py
  pydmd/optdmd.py
  pydmd/paramdmd.py
  pydmd/rdmd.py
  pydmd/snapshots.py
  pydmd/spdmd.py
  pydmd/subspacedmd.py
  tests/test_cdmd.py
  tests/test_dmd.py
  tests/test_dmdbase.py
  tests/test_dmdc.py
  tests/test_hankeldmd.py
  tests/test_havok.py
  tests/test_hodmd.py
  tests/test_mrdmd.py
  tests/test_optdmd.py
  tests/test_rdmd.py
  tests/test_spdmd.py
  tests/test_subspacedmd.py
  tutorials/developers-tutorial1/developers-help-1.ipynb
  tutorials/developers-tutorial1/developers-help-1.py
  tutorials/tutorial7/tutorial-7-dmdc.py
Labels: enhancement, maintenance

#305 Move plot code to `plotter.py`
  pydmd/dmdbase.py
  pydmd/dmdc.py
  pydmd/dmdoperator.py
  pydmd/mrdmd.py
  pydmd/plotter.py
  tests/test_cdmd.py
  tests/test_dmd.py
  tests/test_dmdbase.py
  tests/test_dmdc.py
  tests/test_dmdoperator.py
  tests/test_fbdmd.py
  tests/test_hankeldmd.py
  tests/test_hodmd.py
  tests/test_mrdmd.py
  tests/test_optdmd.py
  tests/test_plotter.py
  tests/test_rdmd.py
  tutorials/developers-tutorial1/developers-help-1.py
  tutorials/tutorial1/tutorial-1-dmd.ipynb
  tutorials/tutorial1/tutorial-1-dmd.py
  tutorials/tutorial12/tutorial-12-cdmd.ipynb
  tutorials/tutorial12/tutorial-12-cdmd.py
  tutorials/tutorial2/tutorial-2-adv-dmd.ipynb
  tutorials/tutorial2/tutorial-2-adv-dmd.py
  tutorials/tutorial3/tutorial-3-mrdmd.ipynb
  tutorials/tutorial3/tutorial-3-mrdmd.py
  tutorials/tutorial5/tutorial-5-fbdmd.ipynb
  tutorials/tutorial5/tutorial-5-fbdmd.py
  tutorials/tutorial6/tutorial-6-hodmd.ipynb
  tutorials/tutorial6/tutorial-6-hodmd.py
  tutorials/tutorial7/tutorial-7-dmdc.ipynb
  tutorials/tutorial7/tutorial-7-dmdc.py
Labels: enhancement, maintenance

#319 Export tutorials in CI
  .github/workflows/export_tutorials.yml
Labels: maintenance

#321 Add comment on SegTrackv2
  .github/workflows/export_tutorials.yml
  .github/workflows/test_tutorials.yml
Labels: maintenance

#322 Add Python 3.9/10. Cache pip test environment
  .github/workflows/ci.yml
  .github/workflows/monthly-tag.yml
  .github/workflows/pypi-publish.yml
  .github/workflows/test_tutorials.yml
  .github/workflows/testing_pr.yml
  setup.py
Labels: maintenance

#308 Added BOP-DMD.
  docs/source/bopdmd.rst
  pydmd/__init__.py
  pydmd/bopdmd.py
  tests/test_bopdmd.py
Labels: dmd-variant

#323 Test `snapshots`, bugfix
  pydmd/snapshots.py
  tests/test_snapshots.py
Labels: minor-bug, maintenance
