Repository PyDMD/PyDMD, pull requests merged in 2023-04, with the labels that each got.

#370 Ignore `SegTrackv2.zip`
  .gitignore
  tutorials/tutorial14/tutorial-14-bop-dmd.ipynb
Labels: maintenance

#374 BOP-DMD RAM usage improvements
  pydmd/bopdmd.py
  tests/test_bopdmd.py
Labels: enhancement, minor-bug, maintenance

#375 Add black checks in PR CI
  .github/workflows/testing_pr.yml
  pydmd/bopdmd.py
  pydmd/hankeldmd.py
  tutorials/tutorial14/tutorial-14-bop-dmd.ipynb
  tutorials/tutorial14/tutorial-14-bop-dmd.py
  tutorials/tutorial3/tutorial-3-mrdmd.py
Labels: maintenance

#379 Add formatter step to the tutorial exporter action
  .github/workflows/export_tutorials.yml
Labels: maintenance

#380 Improvements to ParametricDMD tutorial
  .gitignore
  tutorials/tutorial10/tutorial-10-paramdmd.ipynb
Labels: tutorials

#386 Deploy tutorials to GitHub pages
  .github/workflows/deploy_after_push.yml
Labels: maintenance

#383 Check tutorial references in `tutorials/README.md`
  .github/workflows/testing_pr.yml
  tutorials/README.md
  tutorials/tutorial11/tutorial-11-regularization.ipynb
Labels: maintenance

#400 Fix tutorials testing on `ubuntu-latest` runners
  .github/workflows/testing_pr.yml
Labels: maintenance

#401 Ignore extracted SegTrackv2
  .gitignore
Labels: maintenance
