Repository PyDMD/PyDMD, pull requests merged in 2023-08, with the labels that each got.

#436 DMD fitting with 2 input matrices
  pydmd/dmd.py
  pydmd/dmdbase.py
  tests/test_xyinput.py
Labels: enhancement

#444 Custom input functions for BOP-DMD eigenvalue constraints
  pydmd/bopdmd.py
  tests/test_bopdmd.py
  tests/test_xyinput.py
Labels: enhancement

#445 `PrePostProcessingDMD`
  .github/workflows/testing_pr.yml
  pydmd/__init__.py
  pydmd/hankeldmd.py
  pydmd/havok.py
  pydmd/hodmd.py
  pydmd/preprocessing/__init__.py
  pydmd/preprocessing/hankel.py
  pydmd/preprocessing/pre_post_processing.py
  pydmd/preprocessing/svd_projection.py
  pydmd/preprocessing/zero_mean.py
  pydmd/utils.py
  setup.py
  tests/preprocessing/__init__.py
  tests/preprocessing/test_hankel.py
  tests/preprocessing/test_pre_post_processing.py
  tests/preprocessing/test_zero_mean.py
  tests/test_hankeldmd.py
  tests/test_havok.py
  tests/test_hodmd.py
Labels: enhancement

#448 New module: Kernelized EDMD
  pydmd/__init__.py
  pydmd/edmd.py
  setup.py
  tests/test_edmd.py
  tutorials/README.md
  tutorials/tutorial17/tutorial-17-edmd.ipynb
Labels: dmd-variant

#458 Timeout notebooks run and export when running for too long
  .github/workflows/export_tutorials.yml
  .github/workflows/testing_pr.yml
Labels: maintenance

#459 Apply isort during CI pipeline
  .github/workflows/testing_pr.yml
  pydmd/__init__.py
  pydmd/bopdmd.py
  pydmd/hankeldmd.py
  pydmd/havok.py
  pydmd/hodmd.py
  pydmd/optdmd.py
  pydmd/pidmd.py
  pydmd/pidmd_utils.py
  pydmd/plotter.py
  pydmd/preprocessing/__init__.py
  pydmd/preprocessing/hankel.py
  pydmd/preprocessing/pre_post_processing.py
  pydmd/preprocessing/svd_projection.py
  pydmd/preprocessing/zero_mean.py
  pydmd/snapshots.py
  pydmd/spdmd.py
  pydmd/utils.py
  pyproject.toml
  tests/preprocessing/test_hankel.py
  tests/preprocessing/test_pre_post_processing.py
  tests/preprocessing/test_zero_mean.py
  tests/test_bopdmd.py
  tests/test_dmd_modes_tuner.py
  tests/test_edmd.py
  tests/test_package.py
  tests/test_pidmd.py
  tests/test_xyinput.py
  utils/mathlab_versioning.py
Labels: maintenance

#450 `BOPDMD` updates: discard bad trials and fix eigenvalue sorting
  pydmd/bopdmd.py
  tests/test_bopdmd.py
  tests/test_edmd.py
  tutorials/tutorial14/tutorial-14-bop-dmd.ipynb
Labels: bug, enhancement
